all:: 	test

test:
	@echo ignoring tests for now
	#./TestScenarios.js --calliope Scenarios/*.json
	date > output	# Make sure we have an artifact for our CodeBuild container

monitor:
	./TestScenarios.js --calliope Scenarios/005-JustLogin.json

